# Generated by Django 5.1.7 on 2025-04-30 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_doctor_speciality_alter_patient_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='patient',
            name='matric_number',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
