# Generated by Django 5.1.7 on 2025-05-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_speciality_remove_doctor_speciality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='matric_number',
            field=models.CharField(max_length=9, null=True, unique=True),
        ),
    ]
