# Generated by Django 5.1.7 on 2025-05-04 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_patient_matric_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='speciality',
            new_name='specialities',
        ),
    ]
