# Generated by Django 5.1.7 on 2025-05-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_rename_speciality_doctor_specialities'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='description',
            field=models.TimeField(blank=True, max_length=1000, null=True),
        ),
    ]
