# Generated by Django 5.1.7 on 2025-05-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_speciality_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciality',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
